version: "3.9"
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: '${NS_MARIADB_PASSWORD}'
      MYSQL_USER: '${NS_MARIADB_USER}'
      MYSQL_DATABASE: '${NS_MARIADB_DATABASE}'
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
